# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2019-04-23 06:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReleaseVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=20)),
                ('customer_name', models.CharField(max_length=20)),
                ('customer_id', models.CharField(max_length=10)),
                ('firmware_develop', models.EmailField(max_length=254)),
                ('webui_develop', models.EmailField(max_length=254)),
                ('software_version', models.CharField(max_length=256)),
                ('software_path', models.TextField()),
                ('modification', models.TextField()),
                ('plan_release_date', models.DateTimeField(verbose_name='Plan Release Date')),
                ('actual_release_date', models.DateTimeField(verbose_name='Actual Release Date')),
                ('release_delay_reason', models.TextField()),
                ('self_test_result', models.CharField(max_length=10)),
                ('self_test_fail_reason', models.TextField()),
                ('val_verify_result', models.CharField(max_length=10)),
                ('val_verify_fail_reason', models.TextField()),
                ('create_time', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='releaseversion',
            unique_together=set([('project_name', 'customer_id', 'software_version')]),
        ),
    ]
