# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2019-04-23 06:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vcmapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='releaseversion',
            name='actual_release_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Actual Release Date'),
        ),
        migrations.AlterField(
            model_name='releaseversion',
            name='firmware_develop',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='releaseversion',
            name='modification',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='releaseversion',
            name='plan_release_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Plan Release Date'),
        ),
        migrations.AlterField(
            model_name='releaseversion',
            name='release_delay_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='releaseversion',
            name='self_test_fail_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='releaseversion',
            name='self_test_result',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='releaseversion',
            name='software_path',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='releaseversion',
            name='software_version',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='releaseversion',
            name='val_verify_fail_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='releaseversion',
            name='val_verify_result',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='releaseversion',
            name='webui_develop',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
